/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package muahangonline;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class DangNhap extends javax.swing.JFrame {

    /**
     * Creates new form DangNhap
     */
    public DangNhap() {
        initComponents();
        initComboBox();
    }

    public void initComboBox() {
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        model.addElement("admin");
        model.addElement("manager");
        cbQuyen.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_username = new javax.swing.JTextField();
        btn_dangnhap = new javax.swing.JButton();
        btn_huy = new javax.swing.JButton();
        txt_themTK = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cbQuyen = new javax.swing.JComboBox<>();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Đăng nhập tài khoản");

        jLabel3.setText("Tên đăng nhập");

        jLabel4.setText("Mật khẩu");

        txt_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_usernameActionPerformed(evt);
            }
        });

        btn_dangnhap.setText("Đăng nhập");
        btn_dangnhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dangnhapMouseClicked(evt);
            }
        });
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });

        btn_huy.setText("Hủy");
        btn_huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_huyActionPerformed(evt);
            }
        });

        txt_themTK.setBackground(new java.awt.Color(255, 255, 255));
        txt_themTK.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txt_themTK.setForeground(new java.awt.Color(204, 0, 51));
        txt_themTK.setText("Bạn chưa có tài khoản?");
        txt_themTK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_themTKMouseClicked(evt);
            }
        });

        jLabel5.setText("Quyền hạng");

        cbQuyen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbQuyenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txt_themTK, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_username)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btn_dangnhap)
                                .addGap(18, 18, 18)
                                .addComponent(btn_huy, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                            .addComponent(txt_password)
                            .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbQuyen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_dangnhap)
                    .addComponent(btn_huy))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_themTK)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void btn_dangnhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dangnhapMouseClicked
        // TODO add your handling code here:
        int xacnhan = 1;
        String manager = "manager";
        String admin = "admin";
        String username = txt_username.getText().toString();
        String pass = txt_password.getText().toString();
        if (username.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(this, "Bạn vui lòng nhập đầy đủ thông tin", "Error", 2);
        } else {
            MyConnect myconn = new MyConnect();
            myconn.connect();
            try {
                if (cbQuyen.getSelectedItem().toString() == "admin") {
                    ResultSet rs = myconn.getDataND(username, pass, xacnhan, admin);
                    if (rs.next()) {
                        GUI_quanlyND nd = new GUI_quanlyND();
                        nd.setVisible(true);
                        nd.setLocationRelativeTo(null);
                        nd.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        nd.layND();
                        this.dispose();
                    } else {
                        JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại hoặc chưa được xác nhận bởi người quản trị", "Error", 1);
                        txt_username.setText("");
                        txt_password.setText("");
                        txt_username.requestFocus(); // cho con trỏ trở về username
                    }
                }
                if (cbQuyen.getSelectedItem().toString() == "manager") {
                    ResultSet rs = myconn.getDataND(username, pass, xacnhan, manager);
                    if (rs.next()) {
                        GUI_muahang muahang = new GUI_muahang();
                        muahang.setVisible(true);
                        muahang.setLocationRelativeTo(null);
                        muahang.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                        // in dữ liệu lên table
                        muahang.laySP();
                        muahang.catchRadio();
                        muahang.catchloaiRadio();
                        muahang.catchdonhangRadio();
                        muahang.catchkhachhangRadio();
                        muahang.layLoaiSP();
                        muahang.layDH();
                        muahang.layKH();
                        // JOptionPane.showMessageDialog(this, "Bạn đã đăng nhập thành công", "Đăng nhập", 1);
                        this.dispose();

                    } else {
                        JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại hoặc chưa được xác nhận bởi người quản trị", "Error", 1);
                        txt_username.setText("");
                        txt_password.setText("");
                        txt_username.requestFocus(); // cho con trỏ trở về username
                    }
                }

            } catch (SQLException ex) {
                Logger.getLogger(DangNhap.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn_dangnhapMouseClicked

    private void txt_themTKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_themTKMouseClicked
        // TODO add your handling code here:
//        new DangKy().setVisible(true); // cho bảng mua hàng hiện lên
//        this.dispose();
        DangKy dk = new DangKy();
        dk.setVisible(true);
        dk.pack();
        dk.setLocationRelativeTo(null);
        dk.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();

    }//GEN-LAST:event_txt_themTKMouseClicked

    private void btn_huyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_huyActionPerformed
        // TODO add your handling code here:
        int ret = JOptionPane.showConfirmDialog(null, "Thoát chương trình ?", "Thoát", JOptionPane.YES_OPTION);
        if (ret == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btn_huyActionPerformed

    private void cbQuyenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbQuyenActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_cbQuyenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DangNhap dn = new DangNhap();
                dn.setVisible(true);
                dn.setLocationRelativeTo(null);
                dn.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_huy;
    private javax.swing.JComboBox<String> cbQuyen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JLabel txt_themTK;
    private javax.swing.JTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
